Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 144
Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 144
Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 144
Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 144
Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 144
Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 144
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
TypeError: 'User' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: users_profile.badge_notification

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\collection\views.py", line 30, in home_view
    return render(request, 'collection/index.html', {
        'settings': settings,
    ...<4 lines>...
        'newest_albums': newest_albums,
    })
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 210, in render
    return template.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 56, in render
    result = self.nodelist.render(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 320, in render
    match = condition.eval(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 886, in eval
    return self.value.resolve(context, ignore_failures=True)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\functional.py", line 253, in inner
    return func(_wrapped, *args)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\users\models.py", line 19, in <lambda>
    User.profile = property(lambda u: Profile.objects.get_or_create(user=u)[0])
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ~~~~~~~~^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 645, in get
    num = len(clone)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 382, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: users_profile.badge_notification
"GET /home/ HTTP/1.1" 500 362369
Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 72
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
        request, queryset=cl.get_queryset(request)
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        sender=model,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        origin=self.origin,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 188930
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
        request, queryset=cl.get_queryset(request)
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        sender=model,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        origin=self.origin,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 188364
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 69
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 69
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 69
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 69
Internal Server Error: /integration/test
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\views.py", line 4, in test
    return render(request, 'test.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: test.html
"GET /integration/test HTTP/1.1" 500 89710
Internal Server Error: /integration/test
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\views.py", line 4, in test
    return render(request, 'test.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: test.html
"GET /integration/test HTTP/1.1" 500 89847
Internal Server Error: /integration/test
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\views.py", line 4, in test
    return render(request, 'test.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: test.html
"GET /integration/test HTTP/1.1" 500 89847
Internal Server Error: /integration/test
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\views.py", line 4, in test
    return render(request, 'test.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: test.html
"GET /integration/test HTTP/1.1" 500 89847
Internal Server Error: /integration/test
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\views.py", line 4, in test
    return render(request, 'test.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: test.html
"GET /integration/test HTTP/1.1" 500 89847
Internal Server Error: /integration/test
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\views.py", line 4, in test
    return render(request, 'test.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: test.html
"GET /integration/test HTTP/1.1" 500 90274
Internal Server Error: /integration/test
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\views.py", line 4, in test
    return render(request, 'test.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: test.html
"GET /integration/test HTTP/1.1" 500 90274
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 35, in test_discogs_query
    return render(request, 'integration/test_discogs_query.html', context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 31, in __get__
    value = instance.fetch(self.name)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 245, in fetch
    self.refresh()
    ~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 211, in refresh
    data = self.client._get(self.data['resource_url'])
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 123, in _get
    return self._request('GET', url)
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 115, in _request
    body = json.loads(content.decode('utf8'))
  File "C:\Users\User\miniconda3\envs\music\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\json\decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\json\decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 35, in test_discogs_query
    return render(request, 'integration/test_discogs_query.html', context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 31, in __get__
    value = instance.fetch(self.name)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 245, in fetch
    self.refresh()
    ~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 211, in refresh
    data = self.client._get(self.data['resource_url'])
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 123, in _get
    return self._request('GET', url)
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 115, in _request
    body = json.loads(content.decode('utf8'))
  File "C:\Users\User\miniconda3\envs\music\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\json\decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\json\decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
"GET /integration/test-discogs/ HTTP/1.1" 500 176078
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 40, in test_discogs_query
    return render(request, 'integration/test_discogs_query.html', context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1067, in render
    output = self.filter_expression.resolve(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 718, in resolve
    obj = self.var.resolve(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 31, in __get__
    value = instance.fetch(self.name)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 245, in fetch
    self.refresh()
    ~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 211, in refresh
    data = self.client._get(self.data['resource_url'])
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 123, in _get
    return self._request('GET', url)
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 115, in _request
    body = json.loads(content.decode('utf8'))
  File "C:\Users\User\miniconda3\envs\music\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\json\decoder.py", line 344, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\json\decoder.py", line 362, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
"GET /integration/test-discogs/ HTTP/1.1" 500 176250
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 23, in test_discogs_query
    'year': album.year,
            ^^^^^^^^^^
AttributeError: 'Master' object has no attribute 'year'
"GET /integration/test-discogs/ HTTP/1.1" 500 76205
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 20, in test_discogs_query
    for album in albums:
                 ^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 375, in __iter__
    page = self.page(i)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 347, in page
    data = self.client._get(self._url_for_page(index))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 123, in _get
    return self._request('GET', url)
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 120, in _request
    raise HTTPError(body['message'], status_code)
discogs_client.exceptions.HTTPError: 429: You are making requests too quickly.
"GET /integration/test-discogs/ HTTP/1.1" 500 102000
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 20, in test_discogs_query
    for album in albums:
                 ^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 375, in __iter__
    page = self.page(i)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 347, in page
    data = self.client._get(self._url_for_page(index))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 123, in _get
    return self._request('GET', url)
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 120, in _request
    raise HTTPError(body['message'], status_code)
discogs_client.exceptions.HTTPError: 429: You are making requests too quickly.
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 17, in test_discogs_query
    artist = d.search(artist_name, type='artist')[0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 361, in __getitem__
    page = self.page(page_index)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 347, in page
    data = self.client._get(self._url_for_page(index))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 123, in _get
    return self._request('GET', url)
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 120, in _request
    raise HTTPError(body['message'], status_code)
discogs_client.exceptions.HTTPError: 429: You are making requests too quickly.
"GET /integration/test-discogs/ HTTP/1.1" 500 92222
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 21, in test_discogs_query
    for album in albums:
                 ^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 375, in __iter__
    page = self.page(i)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\models.py", line 347, in page
    data = self.client._get(self._url_for_page(index))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 123, in _get
    return self._request('GET', url)
           ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\discogs_client\client.py", line 120, in _request
    raise HTTPError(body['message'], status_code)
discogs_client.exceptions.HTTPError: 429: You are making requests too quickly.
"GET /integration/test-discogs/ HTTP/1.1" 500 102227
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 24, in test_discogs_query
    'id': album.master_id,
          ^^^^^^^^^^^^^^^
AttributeError: 'Master' object has no attribute 'master_id'
"GET /integration/test-discogs/ HTTP/1.1" 500 76132
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 46, in test_discogs_query
    'id': release_id,
          ^^^^^^^^^^
NameError: name 'release_id' is not defined. Did you mean: 'releases'?
"GET /integration/test-discogs/ HTTP/1.1" 500 77555
Internal Server Error: /integration/test-discogs/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\integration\discogs_query.py", line 45, in test_discogs_query
    album_image = getattr(release, 'thumb', [{}])[0].get('uri', None)  # Get the first album image URL if available
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
"GET /integration/test-discogs/ HTTP/1.1" 500 79137
Internal Server Error: /manage_album/collection/add/
"POST /manage_album/collection/add/ HTTP/1.1" 500 114
Internal Server Error: /home/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: '!followed_artists'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\FOM\Web Technologie\Collection-Tracker\collectionTracker\collection\views.py", line 30, in home_view
    return render(request, 'collection/index.html', {
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '!followed_artists' from '!followed_artists'
"GET /home/ HTTP/1.1" 500 303087
Internal Server Error: /integration/token/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: authenticate() takes 0 positional arguments but 1 was given
"GET /integration/token/ HTTP/1.1" 500 63309
Internal Server Error: /integration/token/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view integration.discogs_query.authenticate didn't return an HttpResponse object. It returned None instead.
"GET /integration/token/ HTTP/1.1" 500 68106
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 108
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 108
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 108
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 108
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\FOM\Web Technologie\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 178042
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\FOM\Web Technologie\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 178042
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\FOM\Web Technologie\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 178042
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\FOM\Web Technologie\Collection-Tracker\collectionTracker\collection\views.py", line 75, in artist_search
    return render(request, 'collection/artist_search.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: collection/artist_search.html
"GET /search/ HTTP/1.1" 500 84867
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 136
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\collection\views.py", line 97, in artist_search
    return render(request, 'collection/artist_search.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: collection/artist_search.html
"GET /search/ HTTP/1.1" 500 92470
Internal Server Error: /search/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\collection\views.py", line 97, in artist_search
    return render(request, 'collection/artist_search.html')
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: collection/artist_search.html
"GET /search/ HTTP/1.1" 500 92470
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: collection_album.discogs_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 2034, in changelist_view
    response = self.response_action(
        request, queryset=cl.get_queryset(request)
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\actions.py", line 39, in delete_selected
    ) = modeladmin.get_deleted_objects(queryset, request)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 2176, in get_deleted_objects
    return get_deleted_objects(objs, request, self.admin_site)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\utils.py", line 138, in get_deleted_objects
    collector.collect(objs)
    ~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\utils.py", line 205, in collect
    return super().collect(objs, source_attr=source_attr, **kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\deletion.py", line 344, in collect
    if getattr(on_delete, "lazy_sub_objs", False) or sub_objs:
                                                     ^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 414, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\sql\compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\backends\sqlite3\base.py", line 354, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: collection_album.discogs_id
"POST /admin/collection/artist/?o=2 HTTP/1.1" 500 230136
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 67
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 55
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 332
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 332
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 104
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 104
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 84
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 67
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 58
Internal Server Error: /admin/collection/album/7J41hCLBI2kEwL6RVSxfNx/change/
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 839, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\models.py", line 654, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\forms\models.py", line 334, in __new__
    raise FieldError(message)
django.core.exceptions.FieldError: Unknown field(s) (versions) specified for Album

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1964, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1820, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 1855, in _changeform_view
    ModelForm = self.get_form(
                ^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\contrib\admin\options.py", line 841, in get_form
    raise FieldError(
django.core.exceptions.FieldError: Unknown field(s) (versions) specified for Album. Check fields/fieldsets/exclude attributes of class AlbumAdmin.
"GET /admin/collection/album/7J41hCLBI2kEwL6RVSxfNx/change/ HTTP/1.1" 500 151073
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 76
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
        request, queryset=cl.get_queryset(request)
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        sender=model,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        origin=self.origin,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 194812
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 83
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
        request, queryset=cl.get_queryset(request)
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        sender=model,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        origin=self.origin,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 178958
Internal Server Error: /admin/collection/artist/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'artist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\sites.py", line 241, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 2058, in changelist_view
    response = self.response_action(
        request, queryset=cl.get_queryset(request)
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1666, in response_action
    response = func(self, request, queryset)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\actions.py", line 49, in delete_selected
    modeladmin.delete_queryset(request, queryset)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\admin\options.py", line 1304, in delete_queryset
    queryset.delete()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 1188, in delete
    num_deleted, num_deleted_per_model = collector.delete()
                                         ~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\deletion.py", line 508, in delete
    signals.post_delete.send(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        sender=model,
        ^^^^^^^^^^^^^
    ...<2 lines>...
        origin=self.origin,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\stats\signals.py", line 80, in award_collection_progress_badge
    artist = instance.album.artist
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
collection.models.Artist.DoesNotExist: Artist matching query does not exist.
"POST /admin/collection/artist/ HTTP/1.1" 500 178958
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 74
Internal Server Error: /album/6p7fGgEP7tBrppR6lru7HX/
"GET /album/6p7fGgEP7tBrppR6lru7HX/ HTTP/1.1" 500 78
Internal Server Error: /album/5URzZroiLUZhdMOwq6KsRk/
"GET /album/5URzZroiLUZhdMOwq6KsRk/ HTTP/1.1" 500 82
Internal Server Error: /album/5URzZroiLUZhdMOwq6KsRk/
"GET /album/5URzZroiLUZhdMOwq6KsRk/ HTTP/1.1" 500 82
Internal Server Error: /album/7vp2iMEQzhNX4sEIUbHpiJ/
"GET /album/7vp2iMEQzhNX4sEIUbHpiJ/ HTTP/1.1" 500 144
Internal Server Error: /album/7vp2iMEQzhNX4sEIUbHpiJ/
"GET /album/7vp2iMEQzhNX4sEIUbHpiJ/ HTTP/1.1" 500 144
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.collection.albums.values_list('artist',"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\users\views.py", line 90, in user_profile
    return render(request, 'users/profile.html', {'user': request.user, 'form': form, 'badges': badges, 'all_badges': all_badges, 'badge_awarded_dates': badge_awarded_dates})
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 1540, in do_with
    nodelist = parser.parse(("endwith",))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('artist',' from 'user.collection.albums.values_list('artist','
"GET /profile/ HTTP/1.1" 500 307597
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.userAlbumCollection.albums.values_list('artist',"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\users\views.py", line 90, in user_profile
    return render(request, 'users/profile.html', {'user': request.user, 'form': form, 'badges': badges, 'all_badges': all_badges, 'badge_awarded_dates': badge_awarded_dates})
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 1540, in do_with
    nodelist = parser.parse(("endwith",))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('artist',' from 'user.userAlbumCollection.albums.values_list('artist','
"GET /profile/ HTTP/1.1" 500 307804
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.useralbumcollection_set.values_list('album__artist',"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\users\views.py", line 90, in user_profile
    return render(request, 'users/profile.html', {'user': request.user, 'form': form, 'badges': badges, 'all_badges': all_badges, 'badge_awarded_dates': badge_awarded_dates})
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 1540, in do_with
    nodelist = parser.parse(("endwith",))
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
    ...<2 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '('album__artist',' from 'user.useralbumcollection_set.values_list('album__artist','
"GET /profile/ HTTP/1.1" 500 307917
Internal Server Error: /album/7jaSNQUBJbvfbZHLNFrV7P/
"GET /album/7jaSNQUBJbvfbZHLNFrV7P/ HTTP/1.1" 500 68
Internal Server Error: /album/7jaSNQUBJbvfbZHLNFrV7P/
"GET /album/7jaSNQUBJbvfbZHLNFrV7P/ HTTP/1.1" 500 61
Internal Server Error: /album/7jaSNQUBJbvfbZHLNFrV7P/
"GET /album/7jaSNQUBJbvfbZHLNFrV7P/ HTTP/1.1" 500 61
Internal Server Error: /album/0AwCgoJKJUOgLp1imhnxuH/
"GET /album/0AwCgoJKJUOgLp1imhnxuH/ HTTP/1.1" 500 205
Internal Server Error: /profile/
Traceback (most recent call last):
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\User\Documents\FOM\WebTech\Collection-Tracker\collectionTracker\users\views.py", line 92, in user_profile
    return render(request, 'users/profile.html', {'user': request.user, 'form': form, 'badges': badges, 'all_badges': all_badges, 'badge_awarded_dates': badge_awarded_dates})
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\miniconda3\envs\music\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
"GET /profile/ HTTP/1.1" 500 239024
Internal Server Error: /artist/DPR IAN/
"GET /artist/DPR%20IAN/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
Internal Server Error: /search/
"POST /search/ HTTP/1.1" 500 147
